# Generated by Django 5.0.6 on 2024-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('born', models.CharField(blank=True, max_length=15, null=True)),
                ('died', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('known_for', models.CharField(blank=True, max_length=255, null=True)),
                ('notable_work', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(max_length=60000)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('medium', models.CharField(blank=True, max_length=250, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('designed_by', models.CharField(blank=True, max_length=250, null=True)),
                ('developer', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor'), ('Admin', 'Admin')], max_length=10)),
            ],
        ),
    ]
