# Generated by Django 5.0.2 on 2024-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='about',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='article',
            name='born',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='died',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='known_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
